platform: linux

image_resource:
  type: docker-image
  source:
    repository: xxx/clitools
    tag: latest

inputs:
  - name: pcf-run-report

params:
  BOSH_ADMIN_CLIENT:
  PCF_SCRT:
  PCF_CERT:
  PCF_ENV:
  RPT_GIT:
  GIT_USER:
  GIT_PASSWORD:
  PCF_DIRECTOR:
  CF_API:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_CLIENT_ID:
  OPSMAN_PASSWORD:
  CLIENT_ID:
  CLIENT_SECRET:
  MGMT_PASS:
  MGMT_USER:

run:
  path: pcf-run-report/tasks/task.sh